# Generated by Django 4.2 on 2023-06-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0005_grocery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grocery',
        ),
        migrations.DeleteModel(
            name='GroceryBooking',
        ),
    ]
