# Generated by Django 4.2 on 2023-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0006_delete_grocery_delete_grocerybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_image', models.ImageField(upload_to='customer_images/')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
    ]
